# Working with `Date` and `Time` in Pandas

In [1]:
import pandas as pd
import datetime as dt

## Review Python's `datetime` module

In [2]:
today = dt.date(2020, 12, 10)

In [3]:
today.year

2020

In [4]:
today.month

12

In [5]:
today.day

10

In [6]:
today1 = dt.datetime(2019, 5, 19, 15, 22, 8)

In [7]:
print(today1)

2019-05-19 15:22:08

In [8]:
today1.hour

15

In [9]:
today1.minute

22

In [10]:
today1.second

8

### `Timestamp`

In [11]:
pd.Timestamp("2015-08-20")

Timestamp('2015-08-20 00:00:00')

In [12]:
pd.Timestamp("2015/08/20")

Timestamp('2015-08-20 00:00:00')

In [13]:
pd.Timestamp("2015, 08, 20")

Timestamp('2015-08-20 00:00:00')

In [14]:
pd.Timestamp("2015-8-20 05:23:45 PM")

Timestamp('2015-08-20 17:23:45')

In [15]:
pd.Timestamp("2015-8-20 05:23:45 AM")

Timestamp('2015-08-20 05:23:45')

In [16]:
df = pd.read_csv("C:\\Users\\ayush\\OneDrive\\Desktop\\ExcelData\\expense.csv")

In [17]:
df.head()

         date  amount     category
0  03/01/2024     520    Groceries
1  07/01/2024     150    Transport
2  15/01/2024     980  Electronics
3  28/01/2024     220       Dining
4  05/02/2024     430         Rent

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      59 non-null     object
 1   amount    59 non-null     int64
 2   category  59 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.5+ KB

### Problem: Date is Still String

Pandas still thinks this is text/string.

So Date operations will NOT work properly.

# Convert String to DateTime

In [19]:
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y')

Now check `datatype:`

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      59 non-null     datetime64[ns]
 1   amount    59 non-null     int64
 2   category  59 non-null     object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 1.5+ KB

### Now Pandas understands:
`This is a real date.`

In [21]:
df.head()

        date  amount     category
0 2024-01-03     520    Groceries
1 2024-01-07     150    Transport
2 2024-01-15     980  Electronics
3 2024-01-28     220       Dining
4 2024-02-05     430         Rent

In [22]:
df1 = df['date'].dt.day
df1.head()

0     3
1     7
2    15
3    28
4     5
Name: date, dtype: int32

In [23]:
df2 = df['date'].dt.month
df2.head()

0    1
1    1
2    1
3    1
4    2
Name: date, dtype: int32

In [24]:
df3 = df['date'].dt.year
df3.head()

0    2024
1    2024
2    2024
3    2024
4    2024
Name: date, dtype: int32

In [25]:
df4 = df['date'].max()
df4

Timestamp('2025-12-22 00:00:00')

In [26]:
df5 = df['date'].min()
df5

Timestamp('2024-01-03 00:00:00')

In [27]:
df6 = df.loc[df['date'] == '2024-03-18']
df6

        date  amount   category
8 2024-03-18     145  Transport

In [28]:
df7 = df.loc[df['date'] < '2024-03-18']
df7

        date  amount     category
0 2024-01-03     520    Groceries
1 2024-01-07     150    Transport
2 2024-01-15     980  Electronics
3 2024-01-28     220       Dining
4 2024-02-05     430         Rent
5 2024-02-11      85    Groceries
6 2024-02-19      60       Snacks
7 2024-03-03     255      Medical

In [29]:
df8 = df.loc[(df['date'] > '2024-03-18') & (df['date'] <'2024-06-21')]
df8

         date  amount   category
9  2024-03-25     600  Groceries
10 2024-04-04     210  Utilities
11 2024-04-22     140     Snacks
12 2024-05-01     700       Rent
13 2024-05-13     475  Groceries
14 2024-05-29     310     Dining
15 2024-06-08     260  Transport

In [30]:
df9 = df.loc[df['date'].between('2024-03-25', '2024-05-13')]
df9

         date  amount   category
9  2024-03-25     600  Groceries
10 2024-04-04     210  Utilities
11 2024-04-22     140     Snacks
12 2024-05-01     700       Rent
13 2024-05-13     475  Groceries

### `Sort` According to date

In [31]:
df10 = df.sort_values('date')
df10.head()

        date  amount     category
0 2024-01-03     520    Groceries
1 2024-01-07     150    Transport
2 2024-01-15     980  Electronics
3 2024-01-28     220       Dining
4 2024-02-05     430         Rent

In [32]:
df11 = df.sort_values('date', ascending=False)
df11.head()

         date  amount   category
58 2025-12-22     110  Transport
57 2025-12-08     160     Snacks
56 2025-11-19     210     Dining
55 2025-11-01     540  Groceries
54 2025-10-21     190  Transport

In [33]:
df12 = df.copy()
df12['Day Name'] = df['date'].dt.day_name()
df12.head()

        date  amount     category   Day Name
0 2024-01-03     520    Groceries  Wednesday
1 2024-01-07     150    Transport     Sunday
2 2024-01-15     980  Electronics     Monday
3 2024-01-28     220       Dining     Sunday
4 2024-02-05     430         Rent     Monday

In [34]:
df13 = df12.copy()
df13['Month Name'] = df['date'].dt.month_name()
df13.head()

        date  amount     category   Day Name Month Name
0 2024-01-03     520    Groceries  Wednesday    January
1 2024-01-07     150    Transport     Sunday    January
2 2024-01-15     980  Electronics     Monday    January
3 2024-01-28     220       Dining     Sunday    January
4 2024-02-05     430         Rent     Monday   February

In [35]:
df14 = df13.copy()
df14['Quatar'] = df['date'].dt.quarter
df14.head()

        date  amount     category   Day Name Month Name  Quatar
0 2024-01-03     520    Groceries  Wednesday    January       1
1 2024-01-07     150    Transport     Sunday    January       1
2 2024-01-15     980  Electronics     Monday    January       1
3 2024-01-28     220       Dining     Sunday    January       1
4 2024-02-05     430         Rent     Monday   February       1

### DateTime with `Time` Component

In [36]:
df15 = pd.read_csv("C:\\Users\\ayush\\OneDrive\\Desktop\\ExcelData\\expense_datetime.csv")

In [37]:
df15.head()

                  date  amount     category
0  2024/01/03 10:24:15     520    Groceries
1  2024/01/07 08:12:44     150    Transport
2  2024/01/15 19:48:03     980  Electronics
3  2024/01/28 13:05:22     220       Dining
4  2024/02/05 09:30:51     430         Rent

In [38]:
df15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      59 non-null     object
 1   amount    59 non-null     int64
 2   category  59 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.5+ KB

In [39]:
df15['date'].dtype

dtype('O')

In [40]:
df15['date'] = pd.to_datetime(df15['date'], format= '%Y/%m/%d  %H:%M:%S')

In [41]:
df15.head()

                 date  amount     category
0 2024-01-03 10:24:15     520    Groceries
1 2024-01-07 08:12:44     150    Transport
2 2024-01-15 19:48:03     980  Electronics
3 2024-01-28 13:05:22     220       Dining
4 2024-02-05 09:30:51     430         Rent

In [42]:
df16 = df15.copy()
df16['Hour'] = df15['date'].dt.hour
df16.head()

                 date  amount     category  Hour
0 2024-01-03 10:24:15     520    Groceries    10
1 2024-01-07 08:12:44     150    Transport     8
2 2024-01-15 19:48:03     980  Electronics    19
3 2024-01-28 13:05:22     220       Dining    13
4 2024-02-05 09:30:51     430         Rent     9

In [43]:
df17 = df16.copy()
df17['Minute'] = df15['date'].dt.minute
df17.head()

                 date  amount     category  Hour  Minute
0 2024-01-03 10:24:15     520    Groceries    10      24
1 2024-01-07 08:12:44     150    Transport     8      12
2 2024-01-15 19:48:03     980  Electronics    19      48
3 2024-01-28 13:05:22     220       Dining    13       5
4 2024-02-05 09:30:51     430         Rent     9      30

In [44]:
df18 = df17.copy()
df18['Second'] = df15['date'].dt.second
df18.head()

                 date  amount     category  Hour  Minute  Second
0 2024-01-03 10:24:15     520    Groceries    10      24      15
1 2024-01-07 08:12:44     150    Transport     8      12      44
2 2024-01-15 19:48:03     980  Electronics    19      48       3
3 2024-01-28 13:05:22     220       Dining    13       5      22
4 2024-02-05 09:30:51     430         Rent     9      30      51

`strftime()`

In [45]:
df19 = df18.copy()

df19['Display Date'] = df15['date'].dt.strftime('%d/%m/%Y %H:%M:%S')

df19.head()

,date,amount,category,Hour,Minute,Second,Display Date
0,2024-01-03 10:24:15,520,Groceries,10,24,15,03/01/2024 10:24:15
1,2024-01-07 08:12:44,150,Transport,8,12,44,07/01/2024 08:12:44
2,2024-01-15 19:48:03,980,Electronics,19,48,3,15/01/2024 19:48:03
3,2024-01-28 13:05:22,220,Dining,13,5,22,28/01/2024 13:05:22
4,2024-02-05 09:30:51,430,Rent,9,30,51,05/02/2024 09:30:51

### `Multiple Date` Operation

In [46]:
df20 = pd.read_csv(r'C:\Users\ayush\OneDrive\Desktop\ExcelData\order_delivery.csv')

df20.head()

  order_date delivery_date  amount     category
0   3/1/2025    06/02/2025     520    Groceries
1   7/1/2025    10/01/2025     150    Transport
2  12/1/2025    14/01/2025     980  Electronics
3  18/1/2025    20/01/2025     220       Dining
4  02/2/2025    05/02/2026     430         Rent

In [47]:
df20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     10 non-null     object
 1   delivery_date  10 non-null     object
 2   amount         10 non-null     int64
 3   category       10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [48]:
df20['order_date'] = pd.to_datetime(df20['order_date'], format='mixed')
df20.head()

  order_date delivery_date  amount     category
0 2025-03-01    06/02/2025     520    Groceries
1 2025-07-01    10/01/2025     150    Transport
2 2025-12-01    14/01/2025     980  Electronics
3 2025-01-18    20/01/2025     220       Dining
4 2025-02-02    05/02/2026     430         Rent

In [49]:
df20['delivery_date'] = pd.to_datetime(df20['delivery_date'], format='mixed')
df20.head()

  order_date delivery_date  amount     category
0 2025-03-01    2025-06-02     520    Groceries
1 2025-07-01    2025-10-01     150    Transport
2 2025-12-01    2025-01-14     980  Electronics
3 2025-01-18    2025-01-20     220       Dining
4 2025-02-02    2026-05-02     430         Rent

In [50]:
df20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     10 non-null     datetime64[ns]
 1   delivery_date  10 non-null     datetime64[ns]
 2   amount         10 non-null     int64
 3   category       10 non-null     object
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 452.0+ bytes

In [51]:
df21 = df20.copy()

df21['Difference'] = df20['delivery_date'] - df20['order_date']
df21.head()

  order_date delivery_date  amount     category Difference
0 2025-03-01    2025-06-02     520    Groceries    93 days
1 2025-07-01    2025-10-01     150    Transport    92 days
2 2025-12-01    2025-01-14     980  Electronics  -321 days
3 2025-01-18    2025-01-20     220       Dining     2 days
4 2025-02-02    2026-05-02     430         Rent   454 days

In [52]:
df22 = df21.copy()

df22['Difference'] = (df20['delivery_date'] - df20['order_date']).dt.days
df22.head()

  order_date delivery_date  amount     category  Difference
0 2025-03-01    2025-06-02     520    Groceries          93
1 2025-07-01    2025-10-01     150    Transport          92
2 2025-12-01    2025-01-14     980  Electronics        -321
3 2025-01-18    2025-01-20     220       Dining           2
4 2025-02-02    2026-05-02     430         Rent         454

### Difference in Two Datetime Columns

In [53]:
df23 = pd.read_csv(r'C:\Users\ayush\OneDrive\Desktop\ExcelData\fast_delivery.csv')

df23.head()

  promised_delivery_time actual_delivery_time
0    2024-07-17 08:52:01  2024-07-17 08:47:01
1    2024-05-28 13:25:29  2024-05-28 13:27:29
2    2024-09-23 13:25:12  2024-09-23 13:29:12
3    2023-11-24 16:34:56  2023-11-24 16:33:56
4    2023-11-20 05:17:39  2023-11-20 05:18:39

In [54]:
df23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   promised_delivery_time  10 non-null     object
 1   actual_delivery_time    10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [55]:
df23['promised_delivery_time'] = pd.to_datetime(df23['promised_delivery_time'], format = 'mixed')

df23.head()

  promised_delivery_time actual_delivery_time
0    2024-07-17 08:52:01  2024-07-17 08:47:01
1    2024-05-28 13:25:29  2024-05-28 13:27:29
2    2024-09-23 13:25:12  2024-09-23 13:29:12
3    2023-11-24 16:34:56  2023-11-24 16:33:56
4    2023-11-20 05:17:39  2023-11-20 05:18:39

In [56]:
df23['actual_delivery_time'] = pd.to_datetime(df23['actual_delivery_time'], format = 'mixed')

df23.head()

  promised_delivery_time actual_delivery_time
0    2024-07-17 08:52:01  2024-07-17 08:47:01
1    2024-05-28 13:25:29  2024-05-28 13:27:29
2    2024-09-23 13:25:12  2024-09-23 13:29:12
3    2023-11-24 16:34:56  2023-11-24 16:33:56
4    2023-11-20 05:17:39  2023-11-20 05:18:39

In [57]:
df23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   promised_delivery_time  10 non-null     datetime64[ns]
 1   actual_delivery_time    10 non-null     datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 292.0 bytes

In [58]:
df24= df23.copy()

df24['Difference'] = df23['promised_delivery_time'] - df23['actual_delivery_time']

df24

  promised_delivery_time actual_delivery_time        Difference
0    2024-07-17 08:52:01  2024-07-17 08:47:01   0 days 00:05:00
1    2024-05-28 13:25:29  2024-05-28 13:27:29 -1 days +23:58:00
2    2024-09-23 13:25:12  2024-09-23 13:29:12 -1 days +23:56:00
3    2023-11-24 16:34:56  2023-11-24 16:33:56   0 days 00:01:00
4    2023-11-20 05:17:39  2023-11-20 05:18:39 -1 days +23:59:00
5    2023-03-18 16:49:51  2023-03-18 16:48:51   0 days 00:01:00
6    2023-04-16 19:01:37  2023-04-16 19:02:37 -1 days +23:59:00
7    2023-06-27 00:38:22  2023-06-27 00:35:22   0 days 00:03:00
8    2024-07-18 14:52:59  2024-07-18 14:51:59   0 days 00:01:00
9    2024-06-10 07:32:02  2024-06-10 07:32:02   0 days 00:00:00

In [59]:
df25= df23.copy()

df25['Difference'] = (df23['promised_delivery_time'] - df23['actual_delivery_time']).dt.total_seconds()

df25

  promised_delivery_time actual_delivery_time  Difference
0    2024-07-17 08:52:01  2024-07-17 08:47:01       300.0
1    2024-05-28 13:25:29  2024-05-28 13:27:29      -120.0
2    2024-09-23 13:25:12  2024-09-23 13:29:12      -240.0
3    2023-11-24 16:34:56  2023-11-24 16:33:56        60.0
4    2023-11-20 05:17:39  2023-11-20 05:18:39       -60.0
5    2023-03-18 16:49:51  2023-03-18 16:48:51        60.0
6    2023-04-16 19:01:37  2023-04-16 19:02:37       -60.0
7    2023-06-27 00:38:22  2023-06-27 00:35:22       180.0
8    2024-07-18 14:52:59  2024-07-18 14:51:59        60.0
9    2024-06-10 07:32:02  2024-06-10 07:32:02         0.0

In [60]:
df26= df24.copy()

df26['Difference'] = df24['Difference'].dt.total_seconds()

df26

  promised_delivery_time actual_delivery_time  Difference
0    2024-07-17 08:52:01  2024-07-17 08:47:01       300.0
1    2024-05-28 13:25:29  2024-05-28 13:27:29      -120.0
2    2024-09-23 13:25:12  2024-09-23 13:29:12      -240.0
3    2023-11-24 16:34:56  2023-11-24 16:33:56        60.0
4    2023-11-20 05:17:39  2023-11-20 05:18:39       -60.0
5    2023-03-18 16:49:51  2023-03-18 16:48:51        60.0
6    2023-04-16 19:01:37  2023-04-16 19:02:37       -60.0
7    2023-06-27 00:38:22  2023-06-27 00:35:22       180.0
8    2024-07-18 14:52:59  2024-07-18 14:51:59        60.0
9    2024-06-10 07:32:02  2024-06-10 07:32:02         0.0

In [61]:
df27= df24.copy()

df27['Difference'] = df26['Difference']/60

df27

  promised_delivery_time actual_delivery_time  Difference
0    2024-07-17 08:52:01  2024-07-17 08:47:01         5.0
1    2024-05-28 13:25:29  2024-05-28 13:27:29        -2.0
2    2024-09-23 13:25:12  2024-09-23 13:29:12        -4.0
3    2023-11-24 16:34:56  2023-11-24 16:33:56         1.0
4    2023-11-20 05:17:39  2023-11-20 05:18:39        -1.0
5    2023-03-18 16:49:51  2023-03-18 16:48:51         1.0
6    2023-04-16 19:01:37  2023-04-16 19:02:37        -1.0
7    2023-06-27 00:38:22  2023-06-27 00:35:22         3.0
8    2024-07-18 14:52:59  2024-07-18 14:51:59         1.0
9    2024-06-10 07:32:02  2024-06-10 07:32:02         0.0

### UNIX timestamps

In [62]:
df28 = pd.read_csv(r'C:\Users\ayush\OneDrive\Desktop\ExcelData\timestamp.csv')

df28.head()

   order_id  order_time  delivery_time
0       101  1732003200     1732005000
1       102  1732100000     1732103600
2       103  1732150000     1732150900
3       104  1732200000     1732207200
4       105  1732250000     1732250300

In [63]:
df28.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5 non-null      int64
 1   order_time     5 non-null      int64
 2   delivery_time  5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [64]:
df28['order_time'] = pd.to_datetime(df28['order_time'], unit = 's')
df28

   order_id          order_time  delivery_time
0       101 2024-11-19 08:00:00     1732005000
1       102 2024-11-20 10:53:20     1732103600
2       103 2024-11-21 00:46:40     1732150900
3       104 2024-11-21 14:40:00     1732207200
4       105 2024-11-22 04:33:20     1732250300

In [65]:
df28['delivery_time'] = pd.to_datetime(df28['delivery_time'], unit = 's')
df28

   order_id          order_time       delivery_time
0       101 2024-11-19 08:00:00 2024-11-19 08:30:00
1       102 2024-11-20 10:53:20 2024-11-20 11:53:20
2       103 2024-11-21 00:46:40 2024-11-21 01:01:40
3       104 2024-11-21 14:40:00 2024-11-21 16:40:00
4       105 2024-11-22 04:33:20 2024-11-22 04:38:20